
server:
  port: 8081
spring:
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto:
        update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url:
      jdbc:mysql://localhost:3306/school?useSSL=false
    username:
      root
    password:
      root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true


